"""Add discount to user table

Revision ID: 4a3b8d65b594
Revises: eb58204d7003
Create Date: 2024-03-24 09:36:35.909465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3b8d65b594'
down_revision: Union[str, None] = 'eb58204d7003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'discount')
    # ### end Alembic commands ###
