"""Add cascade=delete-orphan param to key column in users table

Revision ID: daf79b34984c
Revises: 3f9b0fb13514
Create Date: 2024-04-03 16:05:08.815380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf79b34984c'
down_revision: Union[str, None] = '3f9b0fb13514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tg_id', table_name='users')
    op.drop_column('users', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.create_index('idx_tg_id', 'users', ['tg_id'], unique=False)
    # ### end Alembic commands ###
