"""add new_key column to user

Revision ID: e233b8930b03
Revises: 3a2278a59574
Create Date: 2024-10-24 17:04:25.670415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e233b8930b03'
down_revision: Union[str, None] = '3a2278a59574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_key')
    # ### end Alembic commands ###
