"""Fix imagin text for referral model

Revision ID: fe17ee4826d6
Revises: 4a3b8d65b594
Create Date: 2024-03-26 06:48:13.796108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe17ee4826d6"
down_revision: Union[str, None] = "4a3b8d65b594"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
