"""Add selectin param to user column in referrals table

Revision ID: 56675008e78f
Revises: 3f9b0fb13514
Create Date: 2024-04-03 15:19:07.729491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56675008e78f'
down_revision: Union[str, None] = '3f9b0fb13514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_tg_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tg_id', 'users', ['tg_id'], unique=False)
    op.alter_column('users', 'discount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
